[package]
name = "googlesheets"
version = "0.1.0"
authors = ["chaz-kiker <chaz-kiker@lambdastudents.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
octocrab = "0.9.0"
tokio = { version = "1", features = ["full"] }
anyhow = "1"
fehler = "1"
chrono = "0.4"
url = "2.2.2"
clap = "3.0.0-beta.2"
serde = "^1.0"
serde_json = "^1.0"
yup-oauth2 = "^5.0"
sheets = "0.1.10"
reqwest = "0.11.3"
hyper = "^0.14"
hyper-rustls = "^0.22"
snafu = "0.6.10"
